### ISSUE TITLE
VGG16 Architecture

### ISSUE THREAD

**Issue by MasoomehJasemi** [ARM-software/SCALE-Sim#16]
Hi
Is there network topoplogy csv file for VGG16 model?

Thanks

**Comment by AnandS09** [comment]
We did not include VGG16 yet. Thanks for bringing this up to notice. We will try to include it in the next commit.

**Comment by MasiJ** [comment]
Thanks for your response. May I know the next commit time?

**Comment by wxbbuaa2011** [comment]
Can you guide us make these network topoplog csv file for ResNet50，GoogelNet？or show a detail file about the network topoplogy csv？
