### ISSUE TITLE
Tiny Yolo layer parameters

### ISSUE THREAD

**Issue by Legorock** [ARM-software/SCALE-Sim#17]
Hello,

I noticed that tiny-yolo topology you have is not the same as the followings:
[http://machinethink.net/blog/object-detection-with-yolo/](http://machinethink.net/blog/object-detection-with-yolo/)
[https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-tiny.cfg](https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-tiny.cfg)
Maybe, you are missing the padding in the CSV file?
As far as I know, the IFMAP for the Conv2 should be 208, since Conv1 has the "SAME" padding and there is a 2x2 pooling.

Please let me know if I am mistaken.
Best regards!

**Comment by AnandS09** [comment]
Hi @Legorock, 

Thanks for bringing this to our notice. I will work on this.
