### ISSUE TITLE
Obtaining area and power

### ISSUE THREAD

**Issue by francisco-munoz** [ARM-software/SCALE-Sim#19]
How can I obtain the area and energy from the dram and sram traces generated by SCALE-Sim? I have tried to use DRAMPower but it seems that the trace format is not correct. Do I have to format the traces in order to fit the requested format by DRAMPower?

**Comment by AnandS09** [comment]
Hi @pakiko24 ,

SCALE-Sim's traces follow the following format,
`cycle_num, <address1, address2,...., addressN>`

I think the conversion to DRAMPower's trace format is not too involved from this format. 
@yuhao : Probably you can provide some more insights.

**Comment by pakiko24** [comment]
Hi @AnandS09 ,

Sure, I think it is not difficult to turn the traces into the DRAMPower format. Anyway, could I know exactly how you get the energy and power numbers of your paper?

**Comment by AnandS09** [comment]
Hi @pakiko24, 

For one of our papers, my colleague @yuhao used a script to convert SCALE-Sim traces to DRAMPower. For the arXiv paper, we used got energy per SRAM read/write, DRAM read/write and MAC operation from synthesis. We then used the SCALE-sim traces to calculate energy consumption for the entire operation. Power numbers were then obtained for various frequencies.

**Comment by whatmough** [comment]
It would be good to have this conversion script in the scale sim
repository.  I think it will be very helpful for others also...

**Comment by pakiko24** [comment]
Thank you for your quick answer @AnandS09 ! It is really useful for me. Are you thinking of realising  the scripts soon as @whatmough say? If not, please let me know it and I will code one.

Btw, thank you very much for your excellent simulator.  I am using it and really helps me!

**Comment by whatmough** [comment]
It would be great if you could code one up!!  :)

**Comment by wxbbuaa2011** [comment]
we can obtain the area and energy from the dram and sram traces generated by SCALE-Sim. That's very good.

**Comment by wxbbuaa2011** [comment]
@ whatmough @pakiko24 @AnandS09 How can I obtain the area and energy from the dram and sram traces generated by SCALE-Sim? I also want to konw how to obtain the area and energy. Thank you very much.

**Comment by wxbbuaa2011** [comment]
@ whatmough @pakiko24 How can I obtain the area and energy from the dram and sram traces generated by SCALE-Sim? I also want to konw how to obtain the area and energy. Thank you very much.

**Comment by pakiko24** [comment]
Dear @wxbbuaa2011 ,

you can get area and power by turning the traces into DRAMSimv2 format. You could code a script with that aim.

**Comment by whatmough** [comment]
The power/performance/area modeling aspect is somewhat out of scope for the simulator at the current time.  However, we are open to contributions in this area.
