### ISSUE TITLE
Is there any padding considerations?

### ISSUE THREAD

**Issue by zinechant** [ARM-software/SCALE-Sim#27]
It seems the code default to 'valid' padding, while resnet employs 'same' padding.

**Comment by pakiko24** [comment]
Hi @zinechant , let me try to  answer your question. 

Really, padding does not make sense in SCALE-SIM. The simulator just receives the network architecture through the network file and simulates it using a certain dataflow. Without using the actual values. It just simulates the behaviour of the dataflow based on the network topology. If you want to 'simulate' a padded size, you just have to modify the network architecture file to add as many rows and columns as you wish.

Hope this helps. 

Best regards,
Francisco
email: francisco.munoz2@um.es

**Comment by AnandS09** [comment]
Hi @zinechant ,
@pakiko24 is right, SCALE-Sim expects you to provide padded dimensions in the topology .csv file.

**Comment by zinechant** [comment]
Thanks. Yes, the explanation makes sense.

**Comment by zinechant** [comment]
Sorry, I think there are still issues.

If modifying the input dimension, the number of input values read out from SRAM and DRAM will be changed. I think zero are inserted by any controller rather than read out from SRAM or DRAM in a realistic implementation, 

Of cause, the different is only marginal, but it's not the same.

**Comment by zinechant** [comment]
Sorry, I think there are still issues.

If modifying the input dimension, the number of input values read out from SRAM and DRAM will be changed. I think zero are inserted by any controller rather than read out from SRAM or DRAM in a realistic implementation,

Of cause, the different is only marginal, but it's not the same.
