### ISSUE TITLE
An error about the GoogLe net.csv

### ISSUE THREAD

**Issue by liuhy397** [ARM-software/SCALE-Sim#31]
When I modified the channels number of fc6 from 1024 to 2048, it occurs an error,the command that I input is 
"python scale.py -arch_config=configs/scale.cfg -network=topologies/conv_nets/Googlenet.csv" 
and the results is:
mkdir: cannot create directory ‘./outputs/GoogleTPU_os’: File exists
mkdir: cannot create directory ‘./outputs/GoogleTPU_os/layer_wise’: File exists
mv: cannot stat './outputs/GoogleTPU_os/*sram*': No such file or directory
mv: cannot stat './outputs/GoogleTPU_os/*dram*': No such file or directory

**Comment by msharmavikram** [comment]
Please delete the folder output before running again. I would recommend creating a makefile or script to run these as it becomes very easy.

**Comment by liuhy397** [comment]
> Please delete the folder output before running again. I would recommend creating a makefile or script to run these as it becomes very easy.

I have follow your advice,and i made it,thank you very much
