### ISSUE TITLE
How to print out the number of read and write cycles of on-chip SRAM and DRAM data？

### ISSUE THREAD

**Issue by wxbbuaa2011** [ARM-software/SCALE-Sim#33]
I want to know the read/write cycles for OFM, IFM, weights on SRAM and DRAM. Now, how I do? For example, DRAM IFMAP read:666666 cycles,SRAM IFMAP read:66666 cycles. DRAM OFMAP write:666666 cycles,SRAM OFMAP write:66666 cycles.

**Comment by whatmough** [comment]
This is in the details file that scale sim generates.
