### ISSUE TITLE
Number of bytes for each Read or Write transaction to DRAM.

### ISSUE THREAD

**Issue by donghn** [ARM-software/SCALE-Sim#37]
Hi. I was confused 1 thing. The number of bytes for each transaction (read or write) from DRAM is set to 10 bytes/cycle. Why some parts of trace file the read or write to DRAM is 14 bytes/cycle, and some other just 3bytes/cycles.
Can I combine it to 1 transaction or device it to many transaction? 
For example, we transfer 3000 bytes in 1000 cycles. Instead of transference 3 bytes/cycle Can I transfer  6 bytes every 2 cycles in only 1 cycle and leave idle in another cycle?
It is still true to estimate the Power?
thanks so much.

**Comment by donghn** [comment]
![image](https://user-images.githubusercontent.com/23803918/67018686-8bf30b80-f136-11e9-98d8-579243f69e01.png)
Can we change words_per_cycle to: 
'''
 words_per_cycle  = default_read_bw
'''

**Comment by AnandS09** [comment]
Hi @donghn 

>The number of bytes for each transaction (read or write) from DRAM is set to 10 bytes/cycle.
This is not fixed, it changes based on the read demand for no-stall operation.

>Can I combine it to 1 transaction or device it to many transaction?
>For example, we transfer 3000 bytes in 1000 cycles. Instead of transference 3 bytes/cycle Can I transfer 6 bytes every 2 cycles in only 1 cycle and leave idle in another cycle?
This is not a configurable parameter in SCALE-sim, currently, the tool would spread out the transaction such that BW requirement is not exaggerated.

**Comment by donghn** [comment]
@AnandS09 Thank so much for your reply.
So, you mean read/write to DRAM, do not depend on datawidth of DRAM? (just depend on the demand of operation)? is it true in reality?
As I see in the code. After generate the SRAM trace file. We trace the DRAM write/read from that file. We go through all transactions of SRAM, Whenever the SRAM is full we start to trace the DRAM read/write depending on how many clocks passed and how many bits transferred. So, every clocks we transfer [num_clocks/num_bytes] bytes to DRAM.
am I right? 
If that is true. Can I custom for my DRAM which can read/write 8bytes every cycle?
If not. There is any way to do that?
thank you.

**Comment by whatmough** [comment]
This is basically a simplifying assumption that we use for the simulator.  In practice there is of course a dependence on the DRAM/bus bandwidth.
