### ISSUE TITLE
Can SCALE-sim support Depthwise Convolution?

### ISSUE THREAD

**Issue by louvinci** [ARM-software/SCALE-Sim#38]
Thank you for your share. But I observe the output log file--xxx_sram_write.csv. It seems the number of output is not right when I execute the depthwise convolution. Thanks for your reply！

**Comment by AnandS09** [comment]
Hi @louvinci : 

Thank you for bringing up the requirement. 
We will add this support in SCALE-Sim v2 [https://github.com/scalesim-project/scale-sim-v2]. 

I have opened a new issue in the repo mentioned above.

Thanks
Anand
