### ISSUE TITLE
Bug in sram_traffic_ws.py

### ISSUE THREAD

**Issue by lrh12580** [ARM-software/SCALE-Sim#39]
There might be a bug in sram_traffic_ws.py

Should line 382 and 383
E_w = (ifmap_w - filt_w + stride) / stride 
E_h = (ifmap_h - filt_h + stride) / stride 

be changed to
E_w = math.floor((ifmap_w - filt_w + stride) / stride)
E_h = math.floor((ifmap_h - filt_h + stride) / stride)

Or the E_w and E_h might be floating-point numbers, like 
ifmap_w = 224, filt_w = 11, stride = 4
ifmap_h = 224, filt_h = 11, stride = 4

The generated outputs might be affected by this.

**Comment by AnandS09** [comment]
Hi @lrh12580 ,

Thank you for bringing this into notice. The correct value should be ceiling, I will push this fix along with some other updates in a few days.

Thanks
Anand
