### ISSUE TITLE
Scaling-out

### ISSUE THREAD

**Issue by cansudemirkiran** [ARM-software/SCALE-Sim#48]
Hi, I am wondering how you modeled multiple systolic arrays (partitions) as in your paper here https://cpb-us-w2.wpmucdn.com/sites.gatech.edu/dist/c/332/files/2020/03/scalesim_ispass2020.pdf

I can't see anything about the number of partitions in the code. I assume it's not open source. That would be really helpful for the design space exploration though. There's a formula for cycle count with partitions in the paper, but could you give some hints on how to model the data traffic? Thanks

**Comment by AnandS09** [comment]
Hi @cansudemirkiran : 

Thank you very much for your interest in our work. You are right the scaled-out version is not open sourced yet. 
I am not sure I understand your question on modeling the data traffic. Can you provide some more details on what you are looking for? 
I would be happy to explain. 

Thanks
Anand
