### ISSUE TITLE
  How to get energy through DRAM power

### ISSUE THREAD

**Issue by sys-syj** [ARM-software/SCALE-Sim#56]
Hello:

I want to get the energy , how to generate the format of trace files, for example:

35,ACT,0
50,RDA,0
51,ACT,4
66,RDA,4
86,ACT,0
101,RDA,0
102,ACT,2
117,RDA,2
119,ACT,5
134,RDA,5
137,ACT,0
152,RDA,0
1279,ACT,3
1294,RDA,3
1315,ACT,0
1330,RDA,0
1352,ACT,4
1367,RDA,4
1368,ACT,3
1383,RDA,3
1403,ACT,4
1418,RDA,4
1454,ACT,4
1469,RDA,4
1505,ACT,4
1520,RDA,4
1556,ACT,4
1571,RDA,4
1607,ACT,4
1622,RDA,4
1658,ACT,4
1673,RDA,4
1709,ACT,4
1724,RDA,4
1760,ACT,4
1775,RDA,4
1811,ACT,4
1826,RDA,4
1862,ACT,4
1877,RDA,4
                                                                                                                                                                                             Thanks.

**Comment by AnandS09** [comment]
Hi @sys-syj , 

You can use some custom scripts to convert the SCALE-Sim generated traces to the desirable format. Unfortunately, we do not support conversions to external formats currently and do not have plans to enable such conversions in the near future.

Thanks,
Anand

@whatmough : Please close this issue marking as 'question'
