### ISSUE TITLE
How to map Caffe model to Scale topology (csv) file

### ISSUE THREAD

**Issue by hoangt** [ARM-software/SCALE-Sim#6]
Hi,

I am trying to understand the content of configuration file (.csv) and how to map between SCALE and common CAFFE model

![image](https://user-images.githubusercontent.com/5211028/39007949-1f4cf0d2-43bc-11e8-9b6c-2ec5c8673e9d.png)

Q1: What is the meaning of IFMAP height and IFMAP width parameters and how to select their value per layer?

Q2: Does SCALE model other layers (e.g pooling layers)? The topology CSV file consists only Conv layers

Q3: What is the meaning of Channels parameter? 

 @AnandS09 @yuhao

**Comment by whatmough** [comment]
Won't fix
